name: SupremeItem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.2
        with:
          webhook: ${{ secrets.DISCORD }}
          message: "New commit into **{{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}**."
          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars3.githubusercontent.com/u/32539635?s=400&u=d9038b82096fd87145509d8607fde5d3f551f77e&v=4"} }'
      - name: TriggerJenkinsBuild
        # You may pin to the exact commit or the version.
        # uses: stigmelling/jenkins-action@34d0b732d0b07390079f6c7912c458a777525d1f
        uses: stigmelling/jenkins-action@v1.1
        with:
          # URL to Jenkinsserver
          jenkinsUrl: http://188.34.166.204:8080/
          # Username
          username: admin
          # Token
          token: ${{ secrets.JENKINS_TOKEN }}
          # Name of job
          job: SupremeItem
